package pkg63player;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author tala
 */


public class MainPlayer extends javax.swing.JFrame {

    public boolean debug = true;

    /**
     * Creates new form MainPlayer
     */
    public MainPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFrame = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        CloseButton = new javax.swing.JPanel();
        IconClose = new javax.swing.JLabel();
        Maximize = new javax.swing.JPanel();
        IconMaximize = new javax.swing.JLabel();
        TitleBar = new javax.swing.JPanel();
        TitleText = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        TitleSong = new javax.swing.JLabel();
        TitleArtist = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        Contents = new javax.swing.JPanel();
        Controls = new javax.swing.JPanel();
        Footer = new javax.swing.JPanel();
        Volume = new javax.swing.JPanel();
        VolumeSlider = new javax.swing.JSlider();
        PlaybackControl = new javax.swing.JPanel();
        Shuffle = new javax.swing.JPanel();
        IconShuffle = new javax.swing.JLabel();
        Previous = new javax.swing.JPanel();
        IconPrevious = new javax.swing.JLabel();
        PlayPause = new javax.swing.JPanel();
        IconPlayPause = new javax.swing.JLabel();
        Next = new javax.swing.JPanel();
        IconNext = new javax.swing.JLabel();
        Repeat = new javax.swing.JPanel();
        IconRepeat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainFrame.setPreferredSize(new java.awt.Dimension(720, 50));
        MainFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(30, 30, 220));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseButton.setPreferredSize(new java.awt.Dimension(50, 50));
        CloseButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg63player/img/Close.png"))); // NOI18N
        IconClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconCloseMouseExited(evt);
            }
        });
        CloseButton.add(IconClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 50, 50));

        Header.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 50, 50));

        Maximize.setPreferredSize(new java.awt.Dimension(50, 50));
        Maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaximizeMouseExited(evt);
            }
        });
        Maximize.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconMaximize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg63player/img/Maximize.png"))); // NOI18N
        Maximize.add(IconMaximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 50, 50));

        Header.add(Maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 50, 50));

        TitleText.setFont(new java.awt.Font("Amazon Ember Display Medium", 1, 24)); // NOI18N
        TitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleText.setText("Grooviza");

        javax.swing.GroupLayout TitleBarLayout = new javax.swing.GroupLayout(TitleBar);
        TitleBar.setLayout(TitleBarLayout);
        TitleBarLayout.setHorizontalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleBarLayout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TitleBarLayout.setVerticalGroup(
            TitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        Header.add(TitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 50));

        MainFrame.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        Body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleSong.setFont(new java.awt.Font("Amazon Ember Heavy", 1, 36)); // NOI18N
        TitleSong.setText("Song Name");
        Body.add(TitleSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 40));

        TitleArtist.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TitleArtist.setText("Artist Name");
        Body.add(TitleArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 390, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg63player/img/JavaBackground.png"))); // NOI18N
        Background.setText("jLabel2");
        Body.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 490));

        javax.swing.GroupLayout ContentsLayout = new javax.swing.GroupLayout(Contents);
        Contents.setLayout(ContentsLayout);
        ContentsLayout.setHorizontalGroup(
            ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        ContentsLayout.setVerticalGroup(
            ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        Body.add(Contents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainFrame.add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 720, 360));

        Controls.setBackground(new java.awt.Color(41, 162, 247));
        Controls.setLayout(new java.awt.BorderLayout());

        VolumeSlider.setMaximum(10);
        VolumeSlider.setPaintLabels(true);
        VolumeSlider.setSnapToTicks(true);
        VolumeSlider.setAutoscrolls(true);
        VolumeSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout VolumeLayout = new javax.swing.GroupLayout(Volume);
        Volume.setLayout(VolumeLayout);
        VolumeLayout.setHorizontalGroup(
            VolumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(VolumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        VolumeLayout.setVerticalGroup(
            VolumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VolumeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PlaybackControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Shuffle.setPreferredSize(new java.awt.Dimension(84, 84));
        Shuffle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShuffleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShuffleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ShuffleMouseExited(evt);
            }
        });

        IconShuffle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconShuffle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg63player/img/Close.png"))); // NOI18N

        javax.swing.GroupLayout ShuffleLayout = new javax.swing.GroupLayout(Shuffle);
        Shuffle.setLayout(ShuffleLayout);
        ShuffleLayout.setHorizontalGroup(
            ShuffleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShuffleLayout.createSequentialGroup()
                .addComponent(IconShuffle, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );
        ShuffleLayout.setVerticalGroup(
            ShuffleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShuffleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconShuffle, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );

        PlaybackControl.add(Shuffle, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, -5, 70, 60));

        Previous.setPreferredSize(new java.awt.Dimension(84, 84));
        Previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PreviousMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PreviousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PreviousMouseExited(evt);
            }
        });

        IconPrevious.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg63player/img/Close.png"))); // NOI18N

        javax.swing.GroupLayout PreviousLayout = new javax.swing.GroupLayout(Previous);
        Previous.setLayout(PreviousLayout);
        PreviousLayout.setHorizontalGroup(
            PreviousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        PreviousLayout.setVerticalGroup(
            PreviousLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PreviousLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );

        PlaybackControl.add(Previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, -5, 70, 60));

        PlayPause.setPreferredSize(new java.awt.Dimension(84, 84));
        PlayPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayPauseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PlayPauseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PlayPauseMouseExited(evt);
            }
        });

        IconPlayPause.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg63player/img/Close.png"))); // NOI18N

        javax.swing.GroupLayout PlayPauseLayout = new javax.swing.GroupLayout(PlayPause);
        PlayPause.setLayout(PlayPauseLayout);
        PlayPauseLayout.setHorizontalGroup(
            PlayPauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconPlayPause, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        PlayPauseLayout.setVerticalGroup(
            PlayPauseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayPauseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PlaybackControl.add(PlayPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, -5, 70, 60));

        Next.setPreferredSize(new java.awt.Dimension(84, 84));
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NextMouseExited(evt);
            }
        });

        IconNext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg63player/img/Close.png"))); // NOI18N

        javax.swing.GroupLayout NextLayout = new javax.swing.GroupLayout(Next);
        Next.setLayout(NextLayout);
        NextLayout.setHorizontalGroup(
            NextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconNext, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        NextLayout.setVerticalGroup(
            NextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconNext, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );

        PlaybackControl.add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, -5, 70, 60));

        Repeat.setPreferredSize(new java.awt.Dimension(84, 84));
        Repeat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepeatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RepeatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RepeatMouseExited(evt);
            }
        });

        IconRepeat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconRepeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg63player/img/Close.png"))); // NOI18N

        javax.swing.GroupLayout RepeatLayout = new javax.swing.GroupLayout(Repeat);
        Repeat.setLayout(RepeatLayout);
        RepeatLayout.setHorizontalGroup(
            RepeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconRepeat, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        RepeatLayout.setVerticalGroup(
            RepeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RepeatLayout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(IconRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PlaybackControl.add(Repeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, -5, 70, 60));

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PlaybackControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlaybackControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Volume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Controls.add(Footer, java.awt.BorderLayout.CENTER);

        MainFrame.add(Controls, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 720, 60));

        getContentPane().add(MainFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changeColor(JPanel hover, Color color) {
        hover.setBackground(color);
    }
    
    
    private void IconCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconCloseMouseClicked
        if(debug)
            System.out.println("Exit Button Clicked!");
        System.exit(0);
    }//GEN-LAST:event_IconCloseMouseClicked

    private void IconCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconCloseMouseEntered
        changeColor(CloseButton, new Color(196, 43, 28));
    }//GEN-LAST:event_IconCloseMouseEntered

    private void IconCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconCloseMouseExited
        // TODO add your handling code here:
        changeColor(CloseButton, new Color(214, 217, 223));
    }//GEN-LAST:event_IconCloseMouseExited

    private void MaximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeMouseEntered
        changeColor(Maximize, new Color(153, 153, 153));
    }//GEN-LAST:event_MaximizeMouseEntered

    private void MaximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeMouseExited
        changeColor(Maximize, new Color(214, 217, 223));
    }//GEN-LAST:event_MaximizeMouseExited

    private void MaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizeMouseClicked
        if(debug)
            System.out.println("Maximize Button Clicked!");
    }//GEN-LAST:event_MaximizeMouseClicked

    private void ShuffleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShuffleMouseClicked
        if(debug)
            System.out.println("Shuffle Button Clicked!");
    }//GEN-LAST:event_ShuffleMouseClicked

    private void PreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviousMouseClicked
        if(debug)
            System.out.println("Previous Button Clicked!");
    }//GEN-LAST:event_PreviousMouseClicked

    private void PlayPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayPauseMouseClicked
        if(debug)
            System.out.println("Play/Pause Button Clicked!");
    }//GEN-LAST:event_PlayPauseMouseClicked

    private void NextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseClicked
        if(debug)
            System.out.println("Next Button Clicked!");
    }//GEN-LAST:event_NextMouseClicked

    private void RepeatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepeatMouseClicked
        if(debug)
            System.out.println("Repeat Button Clicked!");
    }//GEN-LAST:event_RepeatMouseClicked

    private void ShuffleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShuffleMouseEntered
        changeColor(Shuffle, new Color(153, 153, 153));
    }//GEN-LAST:event_ShuffleMouseEntered

    private void ShuffleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShuffleMouseExited
        changeColor(Shuffle, new Color(214, 217, 223));
    }//GEN-LAST:event_ShuffleMouseExited

    private void PreviousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviousMouseEntered
        changeColor(Previous, new Color(153, 153, 153));
    }//GEN-LAST:event_PreviousMouseEntered

    private void PreviousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreviousMouseExited
        changeColor(Previous, new Color(214, 217, 223));
    }//GEN-LAST:event_PreviousMouseExited

    private void PlayPauseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayPauseMouseEntered
        changeColor(PlayPause, new Color(153, 153, 153));
    }//GEN-LAST:event_PlayPauseMouseEntered

    private void PlayPauseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayPauseMouseExited
        changeColor(PlayPause, new Color(214, 217, 223));
    }//GEN-LAST:event_PlayPauseMouseExited

    private void NextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseEntered
        changeColor(Next, new Color(153, 153, 153));
    }//GEN-LAST:event_NextMouseEntered

    private void NextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseExited
        changeColor(Next, new Color(214, 217, 223));
    }//GEN-LAST:event_NextMouseExited

    private void RepeatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepeatMouseEntered
        changeColor(Repeat, new Color(153, 153, 153));
    }//GEN-LAST:event_RepeatMouseEntered

    private void RepeatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepeatMouseExited
        changeColor(Repeat, new Color(214, 217, 223));
    }//GEN-LAST:event_RepeatMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel CloseButton;
    private javax.swing.JPanel Contents;
    private javax.swing.JPanel Controls;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel IconClose;
    private javax.swing.JLabel IconMaximize;
    private javax.swing.JLabel IconNext;
    private javax.swing.JLabel IconPlayPause;
    private javax.swing.JLabel IconPrevious;
    private javax.swing.JLabel IconRepeat;
    private javax.swing.JLabel IconShuffle;
    private javax.swing.JPanel MainFrame;
    private javax.swing.JPanel Maximize;
    private javax.swing.JPanel Next;
    private javax.swing.JPanel PlayPause;
    private javax.swing.JPanel PlaybackControl;
    private javax.swing.JPanel Previous;
    private javax.swing.JPanel Repeat;
    private javax.swing.JPanel Shuffle;
    private javax.swing.JLabel TitleArtist;
    private javax.swing.JPanel TitleBar;
    private javax.swing.JLabel TitleSong;
    private javax.swing.JLabel TitleText;
    private javax.swing.JPanel Volume;
    private javax.swing.JSlider VolumeSlider;
    // End of variables declaration//GEN-END:variables
}
