/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg63player;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author tala
 */
public class Splashscreen extends javax.swing.JFrame {
    Timer timer;

    /**
     * Creates new form Splashscreen
     */
    public Splashscreen() {
        initComponents();
    }

    public void Timer(Splashscreen hehe) {
        timer = new Timer(2500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Loading~ Please wait...");
                hehe.dispose();
                System.out.println("Exited Splashscreen!");
                new MainPlayer().setVisible(true);
            }
        });
        timer.setRepeats(false);
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SplashText = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(720, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SplashText.setFont(new java.awt.Font("Amazon Ember Heavy", 1, 48)); // NOI18N
        SplashText.setForeground(new java.awt.Color(141, 115, 128));
        SplashText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SplashText.setText("Grooviza");
        jPanel1.add(SplashText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 720, -1));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg63player/img/JavaBackground.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel SplashText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
